import React from 'react'
import Head from 'next/head'
import { navElementProps } from '../types'
import Header from '../components/Header'
import Nav from '../components/Nav'

const Home = (): JSX.Element => {
  const aboutRef = React.useRef<HTMLDivElement>(null)
  const menuRef = React.useRef<HTMLDivElement>(null)
  const contactRef = React.useRef<HTMLFormElement>(null)

  const navElements: navElementProps[] = [
    { navElementName: 'About', sectionName: aboutRef },
    { navElementName: 'Menu', sectionName: menuRef },
    { navElementName: 'Contact', sectionName: contactRef }
  ]

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header>
        <Nav
          navElements={navElements}
        />
      </Header>
    </>
  )
}


export default Home